kind: Deployment
apiVersion: apps/v1
metadata:
  name: qod-api
  labels:
    app: qod-api
    tier: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qod-api
  template:
    metadata:
      labels:
        app: qod-api
    spec:
      containers:
        - name: qod-api
          image: saianilkumardeyyala/qod-api
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: DB_HOST
              value: qod-db
            - name: DB_USER
              value: user
            - name: DB_PASS
              value: pass
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          imagePullPolicy: Always
      restartPolicy: Always
